name: molgrad
channels:
  - rdkit
  - pytorch
  - dglteam
  - defaults
dependencies:
  - ipython=7.12.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.6
  - pytorch=1.4.0
  - rdkit=2019.09.3.0
  - scipy=1.4.1
  - torchvision=0.5.0
  - tqdm
  - dgl=0.4.3post2
  - dgllife=0.2.3
  - scikit-learn=0.23.1
  - jupyter
  - xlrd
  - lxml
  - seaborn
  - pip:
    - requests==2.23.0
